export const slidesData1 = [
    {
        id: 1,
        image:"https://yourdost.com/blog/wp-content/uploads/2022/07/warriorstory-blog-smrithi-header.png",
        description: "Smrithis Story of Finding Strength In Vulnerability from Therapy",
        tag1: "#LETSTALK",
        tag2: "#YOUARENOTALONE",
    },
    {
        id: 2,
        image:"https://yourdost.com/blog/wp-content/uploads/2022/07/warriorstory-blog-shruthi-header.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus ",
       tag1: "#LETSTALK",
        tag2: "#YOUARENOTALONE",
    },
    {
        id: 3,
        image:"https://yourdost.com/blog/wp-content/uploads/2020/04/Psychological-impact-of-covid-19-pandemic.jpg",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus ",
       tag1: "#LETSTALK",
        tag2: "#YOUARENOTALONE",
    },
    {
        id: 4,
        image:"https://yourdost.com/blog/wp-content/uploads/2020/06/founders-promo1.jpg",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus ",
       tag1: "#LETSTALK",
        tag2: "#YOUARENOTALONE",
    },
    {
        id: 5,
        image:"https://yourdost.com/blog/wp-content/uploads/2020/01/successstory-blog-suhani-cover.jpg",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus ",
       tag1: "#LETSTALK",
        tag2: "#YOUARENOTALONE",
    },
]

export const slidesData2 = [
    {
        id: 1,
        image:"https://yourdost.com/blog/wp-content/uploads/2020/08/A-New-Normal-Life-After-Lockdown-blogheader-1250x654.jpg",
        description: "A New Normal – Life After Lockdown",
       tag1: "#ADVICE",
        tag2: "#CHALLENGES/ISSUES",
    },
    {
        id: 2,
        image:"https://yourdost.com/blog/wp-content/uploads/2020/09/Akshaya-suicidesurvivorstory-blog-cover.jpg",
        description: "On #WorldSuicidePreventionDay,Here Akshaya’s Story",
       tag1: "#LETSTALK",
        tag2: "#YOUARENOTALONE",
    },
]


export const trending = [
    {
        id: 1,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 2,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 3,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 4,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 5,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 6,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 7,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 8,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 9,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 10,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 11,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 12,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 13,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 14,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 15,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 16,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 17,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 18,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 19,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },
    {
        id: 20,
        image:"https://yourdost.com/blog/wp-content/uploads/2023/03/Sai-blog-header-YD-warrior.png",
        description: "Defeating Overthinking and Anxiety and Rediscovering Herself: This is Hema’s Story",
        tag1: "#LETSTALK",
        tag2: "#SILENTWISHPER",
        tag3: "#YOUARENOTALONE",
    },

] 